### ISSUE TITLE
InvalidContentLink

### ISSUE THREAD

**Issue by JuFranze** [microsoft/Customer-Service-Conversational-Insights-with-Azure-OpenAI-Services#115]
The dependency on the ARM template has changed to bicep. 

This causes the error: Unable to download deployment content from '
https://raw.githubusercontent.com/Azure-Samples/cognitive-services-speech-sdk/master/samples/ingestion/ingestion-client/Setup/ArmTemplateBatch.json'.

I

**Comment by JuFranze** [comment]
URL in Customer-Service-Conversational-Insights-with-Azure-OpenAI-Services/blob/infrastructure/ARM/deployment-template.json  is probably: https://raw.githubusercontent.com/Azure-Samples/cognitive-services-speech-sdk/master/samples/ingestion/ingestion-client/infra/main.json

+ I got a version error and the deployment worked when substituting the Version 0301 to 1106
<img width="566" alt="image" src="https://github.com/user-attachments/assets/a3b973c1-3269-4d47-a567-284382722181">

**Comment by megangavin** [comment]
Thank you for your feedback @JuFranze. Our team will review and respond to your logged issue. Your patience is appreciated.

**Comment by Roopan-Microsoft** [comment]
Hi @JuFranze - Issue has been addressed as part of #116 . Please try re-deploying and let us know if any further issues. Thanks.

**Comment by megangavin** [comment]
Closing issue per @Roopan-Microsoft's update above.

**Comment by Roopan-Microsoft** [comment]
@JuFranze - Use ckm-v1 branch to deploy the Version 1.
