### ISSUE TITLE
Function code package for ARM deployment not found

### ISSUE THREAD

**Issue by lenisha** [microsoft/Customer-Service-Conversational-Insights-with-Azure-OpenAI-Services#27]
Trying to deploy ARM template but it fails deploying function from the following package:

https://csciblob.blob.core.windows.net/deploy/csci-audio-dep.zip

It says Blob is disabled
@rturknett @bkeller108 @brittneek 

```[tasklist]
### Tasks
```

**Comment by bkeller108** [comment]
Thank you for reporting this issue. Our team is currently investigating and working diligently towards a resolution. We appreciate your patience during this process.

**Comment by brittneek** [comment]
Thank you for reporting this issue. Our team is currently investigating and working diligently towards a resolution. We appreciate your patience during this process.

**Comment by brittneek** [comment]
This issue has been resolved.
