### ISSUE TITLE
OpenAI Service not invoked by the function while processing documents

### ISSUE THREAD

**Issue by ananth3010** [microsoft/Customer-Service-Conversational-Insights-with-Azure-OpenAI-Services#63]
Hello,

The Function App does not invoke the OpenAI URL using the Prompt key mentioned in the template. When I upload the sample JSON documents, the key-phrases are extracted but every other field is marked as NULL. The keys Agents, Hotels, Call Summary, Customer Satisfaction, Satisfied Customers, Unsatisfied Customers and the fields in the facets are all empty.

These fields are marked as NULL in the Search Index as well. 

The OpenAI prompt looks fine and so does the endpoint & openAI key. There are no errors shown in the function logs as well, so I am not sure where the problem actually lies.

**Comment by ananth3010** [comment]
<img width="1115" alt="image" src="https://github.com/microsoft/Customer-Service-Conversational-Insights-with-Azure-OpenAI-Services/assets/7520928/be3f40be-a4fb-4266-8533-a8fe691e1ba4">

**Comment by megangavin** [comment]
Hello and thank you for logging this issue!

This is a known issue that our engineering team has already identified. All incoming documents are processed in two passes. The first pass extracts the data shown in this screenshot such as keywords, metadata, etc. Then a second pass runs and performs the OpenAI tasks such as gathering sentiment, summary, and the top insights such as hotel and cities mentioned, etc. These passes can be up to 5 mins apart. Thus, conversations can appear "partially processed" during this gap window. Merely refreshing the browser some minutes later would see this resolved.

There is a streamlined solution on our list of backlog items for consideration. As such, we will be closing this issue.
