### ISSUE TITLE
Call Summary & Customer Satisfaction is always null

### ISSUE THREAD

**Issue by Sandeep-FED** [microsoft/Customer-Service-Conversational-Insights-with-Azure-OpenAI-Services#73]
![image](https://github.com/microsoft/Customer-Service-Conversational-Insights-with-Azure-OpenAI-Services/assets/36669540/55534cc7-d0ca-4489-ad76-6be42e45047b)

Have deployed this solution by following the instructions, tried uploading multiple audio files to it but the call summary and customer satisfaction is always returns null.

**Comment by HasanAliPolat** [comment]
Hi @Sandeep-FED, how did you solve this problem ?
